= Poiji
:version: v1.5

image:https://travis-ci.org/ozlerhakan/poiji.svg?branch=master["Build Status", link="https://travis-ci.org/ozlerhakan/poiji"] image:https://api.codacy.com/project/badge/Grade/6587e90886184da29a1b7c5634695c9d["Codacy code quality", link="https://www.codacy.com/app/ozlerhakan/poiji?utm_source=github.com&utm_medium=referral&utm_content=ozlerhakan/poiji&utm_campaign=Badge_Grade"] image:https://coveralls.io/repos/github/ozlerhakan/poiji/badge.svg?branch=master["Coverage Status", link="https://coveralls.io/github/ozlerhakan/poiji?branch=master"] image:https://img.shields.io/badge/license-MIT-blue.svg[]

Poiji is a teeny Java framework that provides one way mapping from Excel sheets to Java classes. In a way it lets us convert each row of the specified excel data into Java objects. Poiji uses https://poi.apache.org/[Apache Poi] (the Java API for Microsoft Documents) under the hood to fulfill the mapping process.

== How it works

In your Maven/Gradle project, first add the corresponding dependency:

.maven
[source,xml]
----
<dependency>
  <groupId>com.github.ozlerhakan</groupId>
  <artifactId>poiji</artifactId>
  <version>1.5</version>
</dependency>
----

.gradle
[source,groovy]
----
dependencies {
    compile 'com.github.ozlerhakan:poiji:1.5'
}
----

You can find the latest and earlier development versions including javadoc and source files on https://oss.sonatype.org/content/groups/public/com/github/ozlerhakan/poiji/[Sonatypes OSS repository].

=== Example 1

Create your object model:

[source,java]
----
public class Employee {

    @ExcelCell(0)                <1>
    private long employeeId;     <2>

    @ExcelCell(1)
    private String name;

    @ExcelCell(2)
    private String surname;

    @ExcelCell(3)
    private int age;

    @ExcelCell(4)
    private boolean single;

    @ExcelCell(5)
    private String birthday;

    //no need getters/setters to map excel cells to fields

    @Override
    public String toString() {
        return "Employee{" +
                "employeeId=" + employeeId +
                ", name='" + name + '\'' +
                ", surname='" + surname + '\'' +
                ", age=" + age +
                ", single=" + single +
                ", birthday='" + birthday + '\'' +
                '}';
    }
}
----
<1> a field must be annotated with `@ExcelCell` along with its property in order to get the value from the right coordinate in the target excel sheet.
<2> an annotated field can be either protected, private or public modifier. The field may be either of `boolean`, `int`, `long`, `float`, `double`, `java.util.Date` or `String`.

This is the excel file (`employees.xlsx`) we want to map to a list of `Employee` instance:

|===
|ID | NAME |SURNAME |AGE |SINGLE |BIRTHDAY

|123923
|Joe
|Doe
|30
|TRUE
|4/9/1987

|123123
|Sophie
|Derue
|20
|TRUE
|5/3/1997

|135923
|Paul
|Raul
|31
|FALSE
|4/9/1986
|===

The snippet below shows how to obtain the excel data using `Poiji`.

[source,java]
----
List<Employee> employees = Poiji.fromExcel(new File("employees.xls"), Employee.class);
employees.size();
// 3
Employee firstEmployee = employees.get(0);
// Employee{employeeId=123923, name='Joe', surname='Doe', age=30, single=true, birthday='4/9/1987'}
----

By default, Poiji ignores the first row of the excel data. You can override this behaviour by setting a `PoijiOptions`.

[source,java]
----
PoijiOptions options = PoijiOptionsBuilder.settings(2).build();
List<Employee> employees = Poiji.fromExcel(new File("employees.xls"), Employee.class, options);
Employee firstEmployee = employees.get(0);
// Employee{employeeId=123123, name='Sophie', surname='Derue', age=20, single=true, birthday='5/3/1997'}
----

By default, Poiji selects the first sheet of an excel file. You can override this behaviour like below:

[source,java]
----
PoijiOptions options = PoijiOptionsBuilder.settings()
                       .sheetIndex(1) <1>
                       .build();
----
1. Poiji should look at the second (zero-based index) sheet of your excel file.


=== Example 2

Your object model may be derived from a super class:

[source,java]
----
public abstract class Vehicle {

    @ExcelCell(0)
    protected String name;

    @ExcelCell(1)
    protected int year;
}

public class Car extends Vehicle {

    @ExcelCell(2)
    private int nOfSeats;
}
----

and you want to map the table (`car.xlsx`) below to Car objects:

|===
|NAME |YEAR |SEATS

|Honda Civic
|2017
|4

|Chevrolet Corvette
|2017
|2
|===

Using Poiji, you can map the annotated field(s) of super class(es) of the target class like so:

[source,java]
----
List<Car> cars = Poiji.fromExcel(new File("cars.xls"), Car.class);
cars.size();
// 2
Car car = cars.get(0);
// Honda Civic
// 2017
// 4
----

== License

MIT
